name: Cloudflare Fixed VPS
on:
  workflow_dispatch: # Chạy thủ công
  schedule:
    - cron: '0 */5 * * *' # Tự động chạy lại mỗi 5 tiếng

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set Password
        run: echo "runner:123" | sudo chpasswd

      - name: Install Cloudflared
        run: |
          curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared.deb

      - name: Start Tunnel
        run: |
          # Kết nối đến Cloudflare bằng Token đã lưu
          cloudflared tunnel --no-autoupdate run --token ${{ secrets.CF_TUNNEL_TOKEN }} &
          # Giữ cho Workflow không bị dừng (chạy trong 6 tiếng)
          sleep 21600
