name: Fixed IP Tunnel
on: [workflow_dispatch]

jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update DuckDNS
        run: |
          # Cập nhật IP máy ảo lên DuckDNS
          curl "https://www.duckdns.org/update?domains=congdongbanthan&token=8fe3c35e-d779-45d3-8851-22e4c6fefaf1&ip="

      - name: Setup Tmate Session
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: false # Cho phép bạn kết nối từ máy tính
